### PR TITLE
Project: Using Bootstrap

### PR DESCRIPTION
**Pull request by LOctavio**
In this project I have cloned the Newsweek page (https://www.newsweek.com)

- I used bootstrap to set the breakpoints with flexbox and girds

### CODE REVIEW

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello! 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ]  Make sure that basic CSS bad practices are not used (article for support ) (screenshot from Pathwright)

no repeating of the same rule
no ID selectors for multiple elements
no !import overusing
no inefficient selectors
no inline styling

- [x] On the navbar, 'sign in' and 'subscribe' need more space between them. 

- [x] Consider making the width of the entire page as the original site. 



Original:


- [x] Consider made the 'more stories' section as the original page.



Original:


**Small screen:**

- [x] 'Top story', 'featured stories', 'opinion', 'the debate', 'more stories', 'culture & travel', 'latest news'  sections has to be in 1 row (each section), consider follow the proportions as the original page for each of these mentioned sections.



Original:


[OPTIONAL]

- [ ] Consider making more space between titles and text, and/or between every section.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @LOctavio, you have done a great job 👍 The project is very responsive on all screen sizes, good use and re-use of bootstrap classes. 🙂 You implemented almost all the comments pointed out by the previous TSE. Before we can proceed, let us address the following comments

* Let us enable stickler for this repo. [Visit](https://stickler-ci.com/)
* Let us apply the DRY rule by refactoring our CSS  file
* Our commits should always be in the present tense. Example: add instead of added, fix instead of fixed
* Let us add our email to the Author section of our README  file

Kindly make these changes and submit another code review 😃 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello! 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Make sure that basic CSS bad practices are not used (article for support ) (screenshot from Pathwright)

--> no repeating of the same rule.

Example:

Screenshot from 2020-03-30 17-41-03

[OPTIONAL]

- [ ] Set your email as the last TSE required, it is not mandatory, but if you are going to leave it please add your email address to the readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by LOctavio** [comment]
Thank you for the review.

In this case, the buttons have the same colors but in different ways. the background color of one button is the color of the other.

image

**Review by MarioDena — APPROVED** [review]
Hello Good job on applying the requested changes!

## Project approved 

## Code review by Mario Enrique Delgado Naranjo

**Pull request merged**
